// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTunnel(arg1) {
  return window['go']['main']['App']['AddTunnel'](arg1);
}

export function BulkImportTunnels(arg1, arg2) {
  return window['go']['main']['App']['BulkImportTunnels'](arg1, arg2);
}

export function CheckDriver() {
  return window['go']['main']['App']['CheckDriver']();
}

export function ClearLogs() {
  return window['go']['main']['App']['ClearLogs']();
}

export function CloseSSHSession(arg1) {
  return window['go']['main']['App']['CloseSSHSession'](arg1);
}

export function CreateSSHSession(arg1) {
  return window['go']['main']['App']['CreateSSHSession'](arg1);
}

export function DeleteSSHConnection(arg1) {
  return window['go']['main']['App']['DeleteSSHConnection'](arg1);
}

export function DeleteSubscription(arg1) {
  return window['go']['main']['App']['DeleteSubscription'](arg1);
}

export function DeleteTunnel(arg1) {
  return window['go']['main']['App']['DeleteTunnel'](arg1);
}

export function GetClientSettings() {
  return window['go']['main']['App']['GetClientSettings']();
}

export function GetDataDir() {
  return window['go']['main']['App']['GetDataDir']();
}

export function GetLaunchOptions() {
  return window['go']['main']['App']['GetLaunchOptions']();
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function GetMachineInfo() {
  return window['go']['main']['App']['GetMachineInfo']();
}

export function GetStats() {
  return window['go']['main']['App']['GetStats']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ImportSubscription(arg1, arg2) {
  return window['go']['main']['App']['ImportSubscription'](arg1, arg2);
}

export function InstallDriver() {
  return window['go']['main']['App']['InstallDriver']();
}

export function IsRunningAsAdmin() {
  return window['go']['main']['App']['IsRunningAsAdmin']();
}

export function IsTUNAccessDenied(arg1) {
  return window['go']['main']['App']['IsTUNAccessDenied'](arg1);
}

export function ListProxyNodes() {
  return window['go']['main']['App']['ListProxyNodes']();
}

export function ListSSHConnections() {
  return window['go']['main']['App']['ListSSHConnections']();
}

export function ListSubscriptions() {
  return window['go']['main']['App']['ListSubscriptions']();
}

export function ListTunnels() {
  return window['go']['main']['App']['ListTunnels']();
}

export function OpenSSHConnectionWindow(arg1) {
  return window['go']['main']['App']['OpenSSHConnectionWindow'](arg1);
}

export function ProxyStatus() {
  return window['go']['main']['App']['ProxyStatus']();
}

export function RefreshAllSubscriptions() {
  return window['go']['main']['App']['RefreshAllSubscriptions']();
}

export function RefreshSubscription(arg1) {
  return window['go']['main']['App']['RefreshSubscription'](arg1);
}

export function RequestAdminRestart() {
  return window['go']['main']['App']['RequestAdminRestart']();
}

export function ResizeSSHSession(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeSSHSession'](arg1, arg2, arg3);
}

export function RecordSSHDebug(arg1, arg2, arg3) {
  return window['go']['main']['App']['RecordSSHDebug'](arg1, arg2, arg3);
}

export function RestartTunnel(arg1) {
  return window['go']['main']['App']['RestartTunnel'](arg1);
}

export function SaveSSHConnection(arg1) {
  return window['go']['main']['App']['SaveSSHConnection'](arg1);
}

export function SendSSHInput(arg1, arg2) {
  return window['go']['main']['App']['SendSSHInput'](arg1, arg2);
}

export function SendSSHInputBase64Batch(arg1, arg2) {
  return window['go']['main']['App']['SendSSHInputBase64Batch'](arg1, arg2);
}

export function SetAutoStartEnabled(arg1) {
  return window['go']['main']['App']['SetAutoStartEnabled'](arg1);
}

export function SetProxyMode(arg1) {
  return window['go']['main']['App']['SetProxyMode'](arg1);
}

export function SetProxyRules(arg1) {
  return window['go']['main']['App']['SetProxyRules'](arg1);
}

export function SetSystemProxyEnabled(arg1) {
  return window['go']['main']['App']['SetSystemProxyEnabled'](arg1);
}

export function StartProxyNode(arg1) {
  return window['go']['main']['App']['StartProxyNode'](arg1);
}

export function StartTunnel(arg1) {
  return window['go']['main']['App']['StartTunnel'](arg1);
}

export function StopProxy() {
  return window['go']['main']['App']['StopProxy']();
}

export function StopTunnel(arg1) {
  return window['go']['main']['App']['StopTunnel'](arg1);
}

export function TestProxyNode(arg1) {
  return window['go']['main']['App']['TestProxyNode'](arg1);
}

export function TestProxyNodes(arg1, arg2) {
  return window['go']['main']['App']['TestProxyNodes'](arg1, arg2);
}

export function ToggleRoute(arg1, arg2) {
  return window['go']['main']['App']['ToggleRoute'](arg1, arg2);
}

export function ToggleSubscription(arg1, arg2) {
  return window['go']['main']['App']['ToggleSubscription'](arg1, arg2);
}

export function UpdateSubscription(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UpdateSubscription'](arg1, arg2, arg3, arg4, arg5);
}

export function UpdateTunnel(arg1, arg2) {
  return window['go']['main']['App']['UpdateTunnel'](arg1, arg2);
}
