// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {tunnel} from '../models';
import {sshsession} from '../models';
import {proxysubscription} from '../models';
import {store} from '../models';
import {manager} from '../models';
import {proxycore} from '../models';
import {main} from '../models';

export function AddTunnel(arg1:config.TunnelCfg):Promise<void>;

export function BulkImportTunnels(arg1:Array<config.TunnelCfg>,arg2:string):Promise<number>;

export function CheckDriver():Promise<tunnel.DriverStatus>;

export function CloseSSHSession(arg1:string):Promise<void>;

export function CreateSSHSession(arg1:sshsession.Config):Promise<string>;

export function DeleteSSHConnection(arg1:string):Promise<void>;

export function DeleteSubscription(arg1:string):Promise<void>;

export function DeleteTunnel(arg1:string):Promise<void>;

export function GetDataDir():Promise<string>;

export function GetClientSettings():Promise<store.ClientSettings>;

export function GetLogs():Promise<Array<main.LogEntry>>;

export function GetStats():Promise<{[key: string]: tunnel.Snapshot}>;

export function GetVersion():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function ImportSubscription(arg1:string,arg2:string):Promise<void>;

export function InstallDriver():Promise<void>;

export function IsRunningAsAdmin():Promise<boolean>;

export function IsTUNAccessDenied(arg1:string):Promise<boolean>;

export function ListProxyNodes():Promise<Array<proxysubscription.ProxyNode>>;

export function ListSSHConnections():Promise<Array<store.SSHConnection>>;

export function ListSubscriptions():Promise<Array<store.SubscriptionSource>>;

export function ListTunnels():Promise<Array<manager.Status>>;

export function ProxyStatus():Promise<proxycore.Status>;

export function ClearLogs():Promise<void>;

export function RequestAdminRestart():Promise<void>;

export function RefreshAllSubscriptions():Promise<[number, number, Array<string>]>;

export function RefreshSubscription(arg1:string):Promise<void>;

export function ResizeSSHSession(arg1:string,arg2:number,arg3:number):Promise<void>;

export function RestartTunnel(arg1:string):Promise<void>;

export function SaveSSHConnection(arg1:store.SSHConnection):Promise<store.SSHConnection>;

export function SendSSHInput(arg1:string,arg2:string):Promise<void>;

export function SetAutoStartEnabled(arg1:boolean):Promise<void>;

export function SetProxyMode(arg1:string):Promise<void>;

export function SetSystemProxyEnabled(arg1:boolean):Promise<void>;

export function StartProxyNode(arg1:string):Promise<void>;

export function StartTunnel(arg1:string):Promise<void>;

export function StopProxy():Promise<void>;

export function StopTunnel(arg1:string):Promise<void>;

export function TestProxyNode(arg1:string):Promise<proxycore.TestResult>;

export function ToggleRoute(arg1:string,arg2:boolean):Promise<void>;

export function ToggleSubscription(arg1:string,arg2:boolean):Promise<void>;

export function UpdateSubscription(arg1:string,arg2:string,arg3:string,arg4:boolean,arg5:number):Promise<void>;

export function UpdateTunnel(arg1:string,arg2:config.TunnelCfg):Promise<void>;
