// Package bootstrap handles first-run setup so the user can launch
// sshtunneld with zero command-line interaction:
//
//   - if the YAML config file is missing, generate a sane default with
//     web.addr=127.0.0.1:8080 and a freshly-generated admin user;
//   - the random plaintext password is written next to the YAML in
//     admin_credentials.txt so the operator can read it once and (ideally)
//     delete it afterwards.
package bootstrap

import (
	"crypto/rand"
	"encoding/base64"
	"fmt"
	"os"
	"path/filepath"
	"runtime"

	"golang.org/x/crypto/bcrypt"
)

// EnsureConfig creates cfgPath (and its directory) if it does not already
// exist.  It returns (created, plaintext, err): created==true means a fresh
// config was just written and plaintext holds the admin password that the
// caller should display once.
func EnsureConfig(cfgPath string) (created bool, plaintext string, err error) {
	if _, statErr := os.Stat(cfgPath); statErr == nil {
		return false, "", nil
	} else if !os.IsNotExist(statErr) {
		return false, "", fmt.Errorf("stat %s: %w", cfgPath, statErr)
	}

	dir := filepath.Dir(cfgPath)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return false, "", fmt.Errorf("mkdir %s: %w", dir, err)
	}

	pw, err := randomPassword(18)
	if err != nil {
		return false, "", err
	}
	hash, err := bcrypt.GenerateFromPassword([]byte(pw), 12)
	if err != nil {
		return false, "", fmt.Errorf("bcrypt: %w", err)
	}

	knownHosts := defaultKnownHosts()
	yaml := fmt.Sprintf(`# Auto-generated by sshtunneld on first run.
# Open the web UI to add tunnels — you should not need to edit this file again.

log_level: info
known_hosts: %s

defaults:
  keepalive_interval: 30s
  keepalive_max_fails: 3
  dial_timeout: 10s
  reconnect_initial: 1s
  reconnect_max: 60s

web:
  addr: 127.0.0.1:8080
  auth:
    # Optional bearer token for scripts/CI.  Leave empty to disable.
    api_token: ""
    users:
      - username: admin
        password_hash: %q
`, knownHosts, string(hash))

	if err := os.WriteFile(cfgPath, []byte(yaml), 0o600); err != nil {
		return false, "", fmt.Errorf("write %s: %w", cfgPath, err)
	}

	credPath := filepath.Join(dir, "admin_credentials.txt")
	body := fmt.Sprintf("sshtunneld admin credentials\n\nURL:      http://127.0.0.1:8080\nUsername: admin\nPassword: %s\n\n"+
		"Delete this file after you have copied the password somewhere safe.\n"+
		"You can rotate the password any time with:  sshtunneld passwd admin\n", pw)
	_ = os.WriteFile(credPath, []byte(body), 0o600)

	return true, pw, nil
}

func randomPassword(n int) (string, error) {
	// 18 raw bytes -> 24 url-safe chars; trim to exactly n for prettier output.
	buf := make([]byte, n)
	if _, err := rand.Read(buf); err != nil {
		return "", fmt.Errorf("rand: %w", err)
	}
	enc := base64.RawURLEncoding.EncodeToString(buf)
	if len(enc) > n {
		enc = enc[:n]
	}
	return enc, nil
}

func defaultKnownHosts() string {
	if runtime.GOOS == "windows" {
		return `${USERPROFILE}\.ssh\known_hosts`
	}
	return "~/.ssh/known_hosts"
}
